# Generated by Django 2.0.5 on 2018-08-02 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('measurement', models.CharField(max_length=30)),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('precio', models.FloatField()),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlatilloIng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Ingrediente')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Platillo')),
            ],
        ),
        migrations.CreateModel(
            name='PlatilloRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Platillo')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('sales_rep', models.CharField(max_length=50)),
                ('sales_rep_phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecetaComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(through='menu.RecetaComp', to='menu.Ingrediente'),
        ),
        migrations.AddField(
            model_name='platillorec',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Receta'),
        ),
        migrations.AddField(
            model_name='platillo',
            name='ingredientes',
            field=models.ManyToManyField(through='menu.PlatilloIng', to='menu.Ingrediente'),
        ),
        migrations.AddField(
            model_name='platillo',
            name='recetas',
            field=models.ManyToManyField(through='menu.PlatilloRec', to='menu.Receta'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Proveedor'),
        ),
    ]
