# Generated by Django 2.0.5 on 2018-08-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='brand',
            field=models.CharField(default='temp', max_length=50),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
