# Generated by Django 2.0.5 on 2018-08-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180803_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
