# Generated by Django 2.0.5 on 2018-08-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20180804_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='bebida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Restaurante'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Restaurante'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Restaurante'),
        ),
    ]
