# Generated by Django 2.0.5 on 2018-08-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20180804_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='nombre',
            field=models.CharField(default='My Platillo', max_length=100),
            preserve_default=False,
        ),
    ]
