# Generated by Django 2.0.5 on 2018-08-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_platillo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='unit_cost',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
