# Generated by Django 2.0.5 on 2018-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_ingrediente_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='unit_cost',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='cost',
            field=models.FloatField(blank=True),
        ),
    ]
