# Generated by Django 2.0.5 on 2018-08-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20180804_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='costo',
            field=models.FloatField(null=True),
        ),
    ]
