# Generated by Django 2.0.5 on 2018-08-05 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20180804_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platilloing',
            name='platillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Platillo'),
        ),
    ]
