# Generated by Django 2.0.5 on 2018-08-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_auto_20180804_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingrediente',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='brand',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='measurement',
            new_name='medida',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='email',
            new_name='correo_electronico',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='sales_rep',
            new_name='representante',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='sales_rep_phone',
            new_name='telefono_de_representante',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='measurement',
            new_name='medida',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='recetacomp',
            old_name='quantity',
            new_name='cantidad',
        ),
    ]
