# Generated by Django 2.0.5 on 2018-08-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20180805_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='marca',
            field=models.CharField(max_length=50),
        ),
    ]
