# Generated by Django 2.0.5 on 2018-08-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_auto_20180805_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='costo',
            field=models.FloatField(),
        ),
    ]
