# Generated by Django 2.0.5 on 2018-08-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_auto_20180805_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platilloing',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='platillorec',
            old_name='quantity',
            new_name='cantidad',
        ),
    ]
