# Generated by Django 2.0.5 on 2018-08-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_platillo_ganancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='ganancia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
