# Generated by Django 2.0.5 on 2018-08-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_auto_20180805_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='ganancia_percentaje',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
