# Generated by Django 2.0.5 on 2018-08-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_platillo_ganancia_percentaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platillo',
            name='ganancia_percentaje',
        ),
        migrations.AddField(
            model_name='platillo',
            name='costo_percentaje',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
