# Generated by Django 2.0.5 on 2018-08-05 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_auto_20180805_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unit_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recetacomp',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Receta'),
        ),
    ]
