# Generated by Django 2.0.5 on 2018-08-05 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_auto_20180805_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillorec',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Receta'),
        ),
    ]
