# Generated by Django 2.0.5 on 2018-08-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_auto_20180805_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetacomp',
            name='medida',
            field=models.CharField(choices=[('oz', 'oz'), ('lb', 'lb'), ('gal', 'gal'), ('L', 'L'), ('mL', 'mL'), ('g', 'g'), ('kg', 'kg'), ('unit', 'unit'), ('dozen', 'dozen')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo_electronico',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_de_representante',
            field=models.IntegerField(verbose_name='Teléfono de representante'),
        ),
    ]
