# Generated by Django 2.0.5 on 2018-08-10 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_auto_20180810_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_de_representante',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono de representante'),
        ),
    ]
