# Generated by Django 2.0.5 on 2018-08-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0033_auto_20180815_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platilloing',
            name='medida',
            field=models.CharField(choices=[('oz', 'oz'), ('lb', 'lb'), ('gal', 'gal'), ('L', 'L'), ('mL', 'mL'), ('g', 'g'), ('kg', 'kg'), ('pieza', 'unit'), ('docena', 'dozen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='platillorec',
            name='medida',
            field=models.CharField(choices=[('oz', 'oz'), ('lb', 'lb'), ('gal', 'gal'), ('L', 'L'), ('mL', 'mL'), ('g', 'g'), ('kg', 'kg'), ('pieza', 'unit'), ('docena', 'dozen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='receta',
            name='medida',
            field=models.CharField(choices=[('oz', 'oz'), ('lb', 'lb'), ('gal', 'gal'), ('L', 'L'), ('mL', 'mL'), ('g', 'g'), ('kg', 'kg'), ('pieza', 'unit'), ('docena', 'dozen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recetacomp',
            name='medida',
            field=models.CharField(choices=[('oz', 'oz'), ('lb', 'lb'), ('gal', 'gal'), ('L', 'L'), ('mL', 'mL'), ('g', 'g'), ('kg', 'kg'), ('pieza', 'unit'), ('docena', 'dozen')], max_length=30),
        ),
    ]
